name: where_to_goes

packages:
  - app
  - core
  - data
  - design
  - di
  - feature/**

scripts:
  test_all:
    run: |
      melos exec -- flutter test
  analyze_all:
    run: |
      melos exec -- flutter analyze