name: home
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  design:
    path: ../../design
  di:
    path: ../../di

  collection: ^1.19.1
  dashed_path: ^1.0.0
  freezed_annotation: ^3.0.0
  flutter_svg: ^2.2.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  build_runner: ^2.5.2

flutter: 
  assets:
    - assets/images/

