name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  data:
    path: ../data
  design:
    path: ../design
  di:
    path: ../di

  home:
    path: ../feature/home
  login:
    path: ../feature/login
  mypage:
    path: ../feature/mypage
  navigation:
    path: ../feature/navigation

  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.12
  kakao_flutter_sdk_user: ^1.9.5
  logger: ^2.6.1
  get_it: ^8.0.3
  go_router: ^16.0.0
  google_sign_in: ^7.1.1

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
