name: design
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
    - family: Yeongdo
      fonts:
        - asset: assets/fonts/YeongdoOTF-Regular.otf
          weight: 400
        - asset: assets/fonts/YeongdoOTF-Bold.otf
          weight: 700
        - asset: assets/fonts/YeongdoOTF-Heavy.otf
          weight: 900
