name: login
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  design:
    path: ../../design
  di:
    path: ../../di

  flutter_svg: ^2.2.0
  get_it: ^8.0.3
  kakao_flutter_sdk_user: ^1.9.5

dev_dependencies:
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/
