name: navigation
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  design:
    path: ../../design
  di:
    path: ../../di

  get_it: ^8.0.3
  collection: ^1.19.1
  flutter_svg: ^2.2.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
