name: navigation
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  design:
    path: ../../design

  collection: ^1.19.1
  flutter_svg: ^2.2.0
  flutter_inappwebview: ^6.1.5
  geolocator: ^14.0.2
  get_it: ^8.0.3
  injectable: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.2
  injectable_generator: ^2.7.0

flutter:
  assets:
    - assets/images/
